export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';

export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';

export const PRODUCT_LIST_ERROR = 'PRODUCT_LIST_ERROR';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';

export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';

export const PRODUCT_DETAILS_ERROR = 'PRODUCT_DETAILS_ERROR';

export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST'

export const ADD_TO_CART = 'ADD_TO_CART'

export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'

export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST'

export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'

export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'

export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'

export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'

export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'

export const USER_UPDATE_ERROR = 'USER_UPDATE_ERROR'

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST'

export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'

export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL'

export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR'

export const USER_PROFILE_UPDATE_REQUEST = 'USER_PROFILE_UPDATE_REQUEST'

export const USER_PROFILE_UPDATE_SUCCESS = 'USER_PROFILE_UPDATE_SUCCESS'

export const USER_PROFILE_UPDATE_ERROR = 'USER_PROFILE_UPDATE_ERROR'

export const SAVE_SHIPPING_ADDRESS = 'SAVE_SHIPPING_ADDRESS'

export const SAVE_PAYMENT_METHOD = 'SAVE_PAYMENT_METHOD'

export const ORDER_SAVE_REQUEST = 'ORDER_SAVE_REQUEST'

export const ORDER_SAVE_SUCCESS = 'ORDER_SAVE_SUCCESS'

export const ORDER_SAVE_ERROR = 'ORDER_SAVE_ERROR'

export const ORDER_GET_REQUEST = 'ORDER_GET_REQUEST'

export const ORDER_GET_SUCCESS = 'ORDER_GET_SUCCESS'

export const ORDER_GET_ERROR = 'ORDER_GET_ERROR'

export const USER_ORDERS_REQUEST = 'USER_ORDERS_REQUEST'

export const USER_ORDERS_SUCCESS = 'USER_ORDERS_SUCCESS'

export const USER_ORDERS_ERROR = 'USER_ORDERS_ERROR'

export const CLEAR_CART = 'CLEAR_CART'

export const ORDER_CLEAR = 'ORDER_CLEAR'

export const PAY_REQUEST = 'PAY_REQUEST'

export const PAY_SUCCESS = 'PAY_SUCCESS'

export const PAY_ERROR = 'PAY_ERROR'

export const CLEAR_PAYMENT = 'CLEAR_PAYMENT'

export const CLEAR_ALL = 'CLEAR_ALL'

export const UPDATE_PROFILE = 'UPDATE_PROFILE'